import { chicagoRules } from '../style/chicago-rules.mjs';

// Catalog metadata describes policy. Availability belongs to each check run;
// registering a rule never implies its detector has been implemented.
const entries = [
   ['LEX-01', 'Forbidden terms and phrases', 'error', 'exact', false,
      'Match configured phrases at defined Unicode word boundaries, respecting allowlists.',
      'We delve into the report.', 'We review the report.'],
   ['LEX-02', 'Empty introductory wording', 'warning', 'heuristic', true,
      'Review introductory wording that adds no information.',
      'It is worth noting that the build failed.', 'The build failed.'],
   ['LEX-03', 'Unsupported benefit language', 'warning', 'semantic', true,
      'Request evidence for vague or inflated benefits; preserve supported claims.',
      'This revolutionary workflow unlocks limitless potential.', 'The supplied trial measured a two-hour reduction.'],
   ['LEX-04', 'Wordy verb phrases', 'suggestion', 'heuristic', true,
      'Prefer a direct verb when a nominalization adds no meaning.',
      'We made a decision to postpone.', 'We decided to postpone.'],
   ['LEX-05', 'Chat residue', 'warning', 'heuristic', true,
      'Identify conversational wrappers inside standalone documents.',
      'Certainly! Here is your revised memo:', 'The team approved the launch.'],
   ['LEX-06', 'Repeated stock transitions', 'warning', 'heuristic', true,
      'Review repeated transition templates for a useful logical connection.',
      'Furthermore, sales rose. Furthermore, costs fell.', 'Sales rose. Costs fell.'],
   ['STR-01', 'Rhetorical contrast framing', 'error', 'heuristic', true,
      'Identify staged this-not-that contrasts, including contrasts split across sentences.',
      'This is not a feature. It is a revolution.', 'The feature reduces upload time.'],
   ['STR-02', 'Parallel padding', 'suggestion', 'semantic', true,
      'Remove redundant parallel items while preserving distinct steps and claims.',
      'It is useful, helpful, and beneficial.', 'The export supports CSV, JSON, and XML.'],
   ['STR-03', 'Repeated sentence templates', 'suggestion', 'heuristic', true,
      'Review repeated openings and paragraph shapes in document context.',
      'It is clear that sales rose. It is clear that costs fell.', 'Sales rose while costs fell.'],
   ['STR-04', 'Redundant closing', 'warning', 'semantic', true,
      'Review closers that restate a point without adding a requested summary or conclusion.',
      'And that is why all of this matters.', 'Approve the revised budget by Friday.'],
   ['STR-05', 'Repeated claims', 'warning', 'semantic', true,
      'Merge repeated claims while preserving qualifications and distinct evidence.',
      'Costs fell. The costs went down.', 'Costs fell. Revenue stayed flat.'],
   ['STR-06', 'Missing substantiation', 'warning', 'semantic', true,
      'Flag unsourced authority or empty emphasis; never supply an invented source.',
      'Experts agree this changes everything.', 'The supplied audit reports three failed checks.'],
   ['GRAM-01', 'Adverbs', 'error', 'heuristic', true,
      'Review grammatical adverbs, including negation and forms without an -ly suffix; recast or report meaning conflicts.',
      'Maya quickly finished.', 'A friendly reviewer finished.'],
   ['CLR-01', 'Passive voice', 'error', 'heuristic', true,
      'Review passive constructions, auxiliary chains, get-passives, and reduced passives without inventing actors.',
      'The report was approved by Maya.', 'Maya approved the report.'],
   ['CLR-02', 'Buried main point', 'warning', 'semantic', true,
      'Review point placement against the audience, purpose, and document structure.',
      'After several unrelated background paragraphs, we finally state the decision.', 'The decision leads the memo.'],
   ['CLR-03', 'Jargon and ambiguous reference', 'suggestion', 'semantic', true,
      'Explain unfamiliar terms and unclear references using supplied context.',
      'This optimizes the thing through synergies.', 'The cache reduces repeat database reads.'],
   ['CLR-04', 'Dense prose', 'suggestion', 'heuristic', true,
      'Review sentence and paragraph burden without splitting essential logical relationships.',
      'The sentence buries its subject inside several nested qualifications before reaching its main verb.', 'The team approved the budget.'],
   ['CLR-05', 'Agentless obligation', 'error', 'semantic', true,
      'Identify duties without a supported actor or unambiguous addressee; preserve modality and report missing owners.',
      'Approval is required before launch.', 'The release manager must approve the launch.'],
   ['READ-01', 'Estimated reading grade', 'warning', 'heuristic', false,
      'Estimate Flesch–Kincaid for eligible English body sentences; report counts, exclusions, undefined pronunciations, and short samples. The metric cannot establish comprehension.',
      'Implementation of the aforementioned methodology necessitates consideration of interdependencies.', 'The team must check how the steps depend on each other.'],
   ['FMT-01', 'Punctuation and decoration overuse', 'suggestion', 'heuristic', true,
      'Review clusters of punctuation, bold labels, or decoration while preserving useful formatting.',
      '**Amazing!** **Powerful!** **Essential!**', 'The report contains three sections.'],
   ['FMT-02', 'Unnecessary fragmentation', 'suggestion', 'semantic', true,
      'Review headings or lists that fragment prose without aiding navigation.',
      '# The point\nThe point.', '# Installation\nFollow these steps.'],
   ['CMO-01', 'Chicago punctuation family', 'warning', 'semantic', true,
      'Screen interior em-dash spacing using the documented Chicago subset; wider punctuation and exceptions require context.',
      'Quotation punctuation needs a source-specific review.', 'A checked punctuation convention has documented evidence.'],
   ['CMO-02', 'Chicago capitalization family', 'warning', 'semantic', true,
      'Review names, titles, and heading conventions; preserve proper names.',
      'Title capitalization varies without a stated convention.', 'The document uses its declared heading convention.'],
   ['CMO-03', 'Chicago spelling and compounds family', 'warning', 'semantic', true,
      'Review US spelling and compound consistency while preserving domain terminology.',
      'The document uses conflicting spellings for the same term.', 'The glossary defines the domain term.'],
   ['CMO-04', 'Chicago numbers family', 'warning', 'semantic', true,
      'Review number presentation under checked guidance without changing values or units.',
      'Equivalent quantities use inconsistent forms.', 'A quantity retains its value and unit.'],
   ['CMO-05', 'Chicago abbreviations family', 'warning', 'semantic', true,
      'Review abbreviation consistency and expansion using supplied definitions.',
      'The text gives two conflicting expansions for one abbreviation.', 'The supplied glossary defines the abbreviation.'],
   ['CMO-06', 'Chicago quotation and citation family', 'warning', 'semantic', true,
      'Review consistency within the chosen citation system while preserving source text and bibliographic facts.',
      'The document mixes citation conventions without a reason.', 'The source quotation remains exact.'],
   ['FID-01', 'Facts and attribution', 'error', 'semantic', true,
      'Compare the candidate to the source; reject changed facts, values, or attribution.',
      'An edit changes 12 participants to 20.', 'The edit retains 12 participants.'],
   ['FID-02', 'Uncertainty and scope', 'error', 'semantic', true,
      'Preserve uncertainty, scope, negation, modality, and comparisons.',
      'An edit changes may reduce to reduces.', 'The edit preserves the uncertainty.'],
   ['FID-03', 'Unsupported additions', 'error', 'semantic', true,
      'Reject unsupported additions when editing a supplied nonfiction draft.',
      'The rewrite invents a personal anecdote.', 'The rewrite adds no unsupported facts.'],
   ['FID-04', 'Protected-content fidelity', 'error', 'exact', false,
      'Reject a proposed edit that changes a protected source span.',
      'A patch changes a quoted number.', 'A patch leaves the exact quotation untouched.'],
   ['FID-05', 'Lost distinctions', 'error', 'semantic', true,
      'Reject edits that merge distinct groups, events, or claims.',
      'The edit merges two separate trial groups.', 'The edit preserves both trial groups.'],
   ['FID-06', 'Voice and register fidelity', 'error', 'semantic', true,
      'Review changes to voice or register and preserve the supplied stance.',
      'A neutral report becomes an invented personal story.', 'The revision retains the neutral register.'],
   ['UNI-01', 'Invisible separators and soft hyphens', 'warning', 'exact', false,
      'Inventory BOM, zero-width spaces, word joiners, and soft hyphens before considering cleanup.',
      're\u200bport', 'report'],
   ['UNI-02', 'Joiners and variation selectors', 'warning', 'exact', false,
      'Inventory joiners and selectors; preserve valid emoji and script shaping.',
      'A joiner outside a recognized sequence needs inspection.', 'A family emoji retains its joiners.'],
   ['UNI-03', 'Bidirectional controls', 'warning', 'exact', false,
      'Inventory directional controls and disclose context; avoid blanket stripping.',
      'An unexplained directional override needs inspection.', 'Mixed-direction text keeps its legitimate controls.'],
   ['UNI-04', 'Special spaces', 'suggestion', 'exact', false,
      'Inventory special spaces; preserve intentional nonbreaking expressions.',
      'An unexpected space character needs inspection.', 'A unit retains its intentional nonbreaking space.'],
   ['UNI-05', 'Tag characters', 'warning', 'exact', false,
      'Inspect tag sequences while preserving valid emoji sequences and literal examples.',
      'An unexplained tag sequence needs inspection.', 'A valid emoji tag sequence remains intact.'],
   ['UNI-06', 'Combining and compatibility characters', 'suggestion', 'exact', false,
      'Report relevant character context without global normalization or homoglyph substitution.',
      'An unexplained compatibility character needs inspection.', 'A name retains its combining accent.'],
   ['ART-01', 'Citation and transport artifacts', 'warning', 'heuristic', true,
      'Review model transport placeholders; preserve or resolve citations from supplied sources.',
      'An unresolved model citation marker appears in a memo.', 'The memo cites the supplied source.'],
];

const categories = { LEX: 'wording', STR: 'structure', GRAM: 'grammar', CLR: 'clarity', READ: 'readability', FMT: 'formatting', CMO: 'chicago', FID: 'fidelity', UNI: 'unicode', ART: 'artifacts' };
export function deepFreeze(value) {
   if (value && typeof value === 'object') {
      for (const child of Object.values(value)) deepFreeze(child);
      Object.freeze(value);
   }
   return value;
}

export const houseBanIds = Object.freeze(['GRAM-01', 'CLR-01', 'CLR-05', 'STR-01']);
export const rules = deepFreeze(entries.map(([id, title, defaultSeverity, type, requiresContext, criteria, finding, clear]) => ({
   id, version: /^(UNI-|CMO-|READ-)/.test(id) ? '1.1.0' : '1.0.0', category: categories[id.split('-')[0]], title,
   rationale: id.startsWith('FID-') ? 'Edits must preserve source meaning and protected content.' : 'Apply the declared prose policy with evidence and preserve meaning.',
   sources: [{ reference: 'docs/RULES.md', kind: 'project-policy' },
      ...(id.startsWith('UNI-') ? [{ reference: 'https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-23/', kind: 'external-reference' }] : []),
      ...(id === 'READ-01' ? [{ reference: 'https://support.microsoft.com/en-us/outlook/get-your-email-s-readability-and-level-statistics', kind: 'external-reference' }] : []),
      ...chicagoRules.filter((rule) => rule.ruleId === id).map((rule) => ({ reference: rule.reference, kind: 'external-reference' }))],
   defaultSeverity, detector: {
      type, requiresContext,
      ...(['GRAM-01', 'CLR-01'].includes(id) ? { subtype: 'grammar' } : {}),
      ...(id === 'READ-01' ? { subtype: 'metric' } : {}),
   },
   scopes: [id.startsWith('FID-') ? 'edit' : id.startsWith('UNI-') ? 'source' : 'prose'],
   criteria,
   exceptions: id.startsWith('FID-') ? [] : ['Preserve protected content and report conflicts.', 'Honor a valid explicit suppression without concealing it.'],
   fixPolicy: id === 'UNI-01' ? 'safe-local' : id === 'READ-01' || id === 'FID-04' || id.startsWith('UNI-') ? 'report-only' : 'editorial-review',
   examples: [{ text: finding, outcome: 'review', reason: criteria }, { text: clear, outcome: 'preserve', reason: 'Preserve this content or distinction in context.' }],
})));
export const ruleIds = Object.freeze(rules.map((rule) => rule.id));
export const ruleById = deepFreeze(Object.fromEntries(rules.map((rule) => [rule.id, rule])));
